docker@run-services:
	docker-compose -p flashcards-app --project-directory ./ \
	-f $(_DOCKER_COMPOSE_FILES)/docker-compose-dev.yaml build

	docker-compose -p flashcards-app --project-directory ./ \
	-f $(_DOCKER_COMPOSE_FILES)/docker-compose-dev.yaml up -d


