FROM node:alpine

RUN mkdir /app

WORKDIR /app

COPY backend/package.json backend/yarn.lock ./
COPY backend/tsconfig.json backend/tsconfig.json ./
COPY backend/tsconfig.build.json backend/tsconfig.build.json ./

COPY backend/src /app/src

RUN yarn install

CMD [ "yarn", "start" ]

EXPOSE 8080
