version: "3.8"

services:
  backend:
    container_name: flashcards-app-backend
    build:
      dockerfile: ./devtools/dockerfiles/backend/Dockerfile.dev
      context: .
    command: ["yarn", "start"]
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file: ./backend/.env

  postgres:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
